### ISSUE TITLE
Variable text width

### ISSUE THREAD

**Issue by renderdender** [lucasepe/crumbs#3]
Hey guys, is there any easy way to change the width of text in the nodes? I usually end up with pretty large text blocks at the end nodes of mindmap and the text is formatted so that each line is just a few words. I'd like to make them a bit wider. Could you maybe give me some direction where to look if you remember the project good enough?

**Comment by lucasepe** [comment]
Hi! 

Have you tried using the `--lim` flag option?

```
-lim uint
    	wraps each line within this width in characters (default 28)
```

**Comment by renderdender** [comment]
@lucasepe Oops. I think I tried to hardcode the same thing, but it didn't work for some reason. From command line it works just fine. Thanks!
